apiVersion: v1
kind: Pod
metadata:
  name: wangjian-zero-1
  namespace: default
  labels:
    app: myzero
    tier: frontend
spec:
  containers:
    - name: myzero
      imagePullPolicy: IfNotPresent
      image: wangjianqutoutiao/wangjian-zero:v0.0.01
      ports:
        - name: http
          containerPort: 8888

