apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myzero
    release: frontend
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30080